### ISSUE TITLE
Pharo 7 ?

### ISSUE THREAD

**Issue by svenvc** [DraagrenKirneh/PngSuiteExplorer#1]
In Pharo 7 the image read writers expect pure/simple binary streams.

#initialize should do the reading as follows

 (PNGReadWriter formFromStream: data asByteArray readStream) asMorph 

And yes, ZipArchive needs to be patched as well. It is wrong to assume the data inside a .zip to be strings, it is just binary data.

**Comment by DraagrenKirneh** [comment]
>And yes, ZipArchive needs to be patched as well. It is wrong to assume the data inside a .zip to be strings, it is just binary data.

Where is this assumption made? 
In #DownloadAndExtract the assumtion is that the response is binary.

Added #2 to fix the initialization.

**Comment by svenvc** [comment]
When you iterate over the members and say #contents, you get a string back.
The deprecated RWBinaryOrTextStream masks that fact by being bivalent.
In Pharo 7 the image read writers expect pure/simple binary streams.
They don't send #binary first because it is not needed (and neither do the send #reset anymore).

**Comment by DraagrenKirneh** [comment]
Ah ok. 
I will change the file contents to bytearray instead of in the initialization then.
